import pg from "pg";
import { AsyncLocalStorage } from "node:async_hooks";

const { Pool } = pg;

// AsyncLocalStorage to track which client is being used inside a transaction.
// This allows run/get/all to automatically use the transaction client when
// called inside a db.transaction() callback, without changing the call-site API.
const txContext = new AsyncLocalStorage();

/**
 * Translate SQLite-style `?` placeholders to PostgreSQL `$1, $2, ...`.
 */
function translatePlaceholders(sql) {
  let idx = 0;
  return sql.replace(/\?/g, () => `$${++idx}`);
}

/**
 * Translate SQLite DDL / DML quirks to PostgreSQL equivalents.
 * Called on every statement so it must be fast for the common (no-op) case.
 */
function translateSql(sql) {
  let s = sql;

  // Skip PRAGMA statements entirely
  if (/^\s*PRAGMA\b/i.test(s)) return null;

  // AUTOINCREMENT → GENERATED BY DEFAULT AS IDENTITY
  s = s.replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");

  // INSERT OR REPLACE → INSERT ... ON CONFLICT DO UPDATE (basic rewrite)
  // This handles the pattern: INSERT OR REPLACE INTO table(cols) VALUES(...)
  s = s.replace(/\bINSERT\s+OR\s+REPLACE\s+INTO\s+(\w+)\s*\(([^)]+)\)\s*VALUES\s*\(([^)]+)\)/gi,
    (match, table, cols, vals) => {
      const colList = cols.split(",").map(c => c.trim());
      // Assume first column is the primary key for ON CONFLICT
      const pk = colList[0];
      const updates = colList.slice(1).map(c => `${c} = EXCLUDED.${c}`).join(", ");
      return `INSERT INTO ${table}(${cols}) VALUES(${vals}) ON CONFLICT(${pk}) DO UPDATE SET ${updates}`;
    }
  );

  // REAL → DOUBLE PRECISION (in DDL only, safe to apply broadly)
  s = s.replace(/\bREAL\s+DEFAULT\b/gi, "DOUBLE PRECISION DEFAULT");
  s = s.replace(/\bREAL\b(?!\s+DEFAULT)/gi, (match, offset) => {
    // Only replace in DDL context (near column definitions)
    // Check if this looks like a CREATE/ALTER statement
    if (/\b(CREATE|ALTER)\b/i.test(s)) return "DOUBLE PRECISION";
    return match;
  });

  // Translate ? placeholders to $1, $2, ...
  s = translatePlaceholders(s);

  return s;
}

/**
 * Split a multi-statement SQL string by semicolons (for exec()).
 * Respects single-quoted strings.
 */
function splitStatements(sql) {
  const stmts = [];
  let current = "";
  let inString = false;
  for (let i = 0; i < sql.length; i++) {
    const ch = sql[i];
    if (ch === "'" && !inString) { inString = true; current += ch; }
    else if (ch === "'" && inString) {
      // Check for escaped quote ''
      if (sql[i + 1] === "'") { current += "''"; i++; }
      else { inString = false; current += ch; }
    }
    else if (ch === ";" && !inString) {
      if (current.trim()) stmts.push(current.trim());
      current = "";
    }
    else { current += ch; }
  }
  if (current.trim()) stmts.push(current.trim());
  return stmts;
}

const COLUMN_MAP = {
  authtype: "authType",
  isactive: "isActive",
  createdat: "createdAt",
  updatedat: "updatedAt",
  teststatus: "testStatus",
  machineid: "machineId",
  datekey: "dateKey",
  prompttokens: "promptTokens",
  completiontokens: "completionTokens",
  connectionid: "connectionId",
  apikey: "apiKey",
};

function normalizeRow(row) {
  if (!row || typeof row !== "object") return row;
  const out = { ...row };
  for (const [key, val] of Object.entries(row)) {
    const mapped = COLUMN_MAP[key];
    if (mapped && !(mapped in out)) {
      out[mapped] = val;
    }
  }
  return out;
}

export async function createPgAdapter(connectionString) {
  const pool = new Pool({
    connectionString,
    max: 10,
    idleTimeoutMillis: 30000,
    connectionTimeoutMillis: 5000,
  });

  // Test connection
  const testClient = await pool.connect();
  testClient.release();

  function getClient() {
    return txContext.getStore() || pool;
  }

  const adapter = {
    driver: "pg",
    isAsync: true,

    async run(sql, params = []) {
      const translated = translateSql(sql);
      if (!translated) return { changes: 0 };
      const client = getClient();
      const result = await client.query(translated, params);
      return { changes: result.rowCount || 0 };
    },

    async get(sql, params = []) {
      const translated = translateSql(sql);
      if (!translated) return null;
      const client = getClient();
      const result = await client.query(translated, params);
      return result.rows[0] ? normalizeRow(result.rows[0]) : null;
    },

    async all(sql, params = []) {
      const translated = translateSql(sql);
      if (!translated) return [];
      const client = getClient();
      const result = await client.query(translated, params);
      return result.rows.map(normalizeRow);
    },

    async exec(sql) {
      const stmts = splitStatements(sql);
      const client = getClient();
      for (const stmt of stmts) {
        const translated = translateSql(stmt);
        if (translated) await client.query(translated);
      }
    },

    async transaction(fn) {
      const client = await pool.connect();
      await client.query("BEGIN");
      try {
        const result = await txContext.run(client, fn);
        await client.query("COMMIT");
        return result;
      } catch (e) {
        await client.query("ROLLBACK");
        throw e;
      } finally {
        client.release();
      }
    },

    checkpoint() { /* no-op for PG */ },

    async close() {
      await pool.end();
    },

    raw: pool,
  };

  return adapter;
}
